package com.civicpulse.servicemanagement.entity;

public enum ServiceType {
    BIRTH_CERTIFICATE,
    DEATH_CERTIFICATE,
    INCOME_CERTIFICATE,
    RESIDENCE_CERTIFICATE,
    TRADE_LICENSE,
    PERMIT_APPROVAL,
    COMMUNITY_CERTIFICATE,
    BUILDING_PERMIT,
    ROAD_CUTTING_PERMIT,
    WATER_CONNECTION_PERMIT,
    ELECTRICITY_CONNECTION_PERMIT,
    PUBLIC_EVENT_PERMIT
}
